server:
  port: 8770
  servlet:
    context-path: /pasture-common
eureka:
  client:
    serviceUrl:
      defaultZone: http://server2:8777/eureka/,http://server1:8761/eureka/

mybatis-plus:
  type-aliases-package: com.example.pasturecommon.model
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: /pasture-common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pasture?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    password: 123456
  redis:
    database: 16
    timeout: 2000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
#    pool:
#    max-active: 8
#    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    max-wait: -1
#    # 连接池中的最大空闲连接
#    max-idle: 8
#    # 连接池中的最小空闲连接

#logging:
#  file:
#    path: /data/logs/${spring.application.name}
#  config: classpath:logback-spring.xml