#################################线上环境配置#################################
###################################基础配置###################################

########mq 配置########
rabbitmq
  username:
  host:
  port:
  password:
  virtual:
    host:


test:
  #交换机
  rabbitmq:
    exchange:
  #测试消息配置
  route:
    key:
  queue:

########数据库########
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
